/** NativaCare embeddable chat widget. */
(function () {
  "use strict";
  var thisScript=document.currentScript;
  var API_BASE=(thisScript&&thisScript.getAttribute("data-api-url"))||(thisScript&&new URL(thisScript.src).origin)||"";
  var CLINIC_NAME=(thisScript&&thisScript.getAttribute("data-clinic-name"))||"NativaCare";
  var SESSION_KEY="nativacareWidgetSessionId";
  if(!API_BASE){console.error("[NativaCare widget] Backend URL unavailable");return;}
  function getSessionId(){try{var id=localStorage.getItem(SESSION_KEY);if(!id){id="web_"+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem(SESSION_KEY,id);}return id;}catch(e){return "web_"+Math.random().toString(36).slice(2);}}
  var css=`#nativacare-widget-root,#nativacare-widget-root *{box-sizing:border-box}#nativacare-widget-root{position:fixed;bottom:20px;right:20px;z-index:2147483000;font-family:Inter,-apple-system,'Segoe UI',sans-serif}#nc-bubble{width:60px;height:60px;border-radius:999px;border:0;cursor:pointer;background:#765a14;color:#fff;box-shadow:0 8px 24px rgba(118,90,20,.35);display:flex;align-items:center;justify-content:center}#nc-panel{position:absolute;bottom:76px;right:0;width:360px;max-width:calc(100vw - 32px);height:520px;max-height:calc(100vh - 120px);background:#F9F8F6;border-radius:20px;box-shadow:0 16px 48px rgba(0,0,0,.18);border:1px solid #E5E7EB;display:none;flex-direction:column;overflow:hidden}#nc-panel.open{display:flex}#nc-header{background:#765a14;color:#fff;padding:16px 18px;display:flex;align-items:center;justify-content:space-between;flex-shrink:0}#nc-header-title{font-weight:700;font-size:15px}#nc-header-sub{font-size:11px;opacity:.8;margin-top:1px}#nc-close{background:none;border:0;color:#fff;cursor:pointer;padding:4px}#nc-messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:10px}.nc-msg{max-width:82%;padding:10px 13px;border-radius:14px;font-size:13.5px;line-height:1.45;white-space:pre-wrap}.nc-msg-bot{align-self:flex-start;background:#fff;border:1px solid #E5E7EB;color:#1a1c1e;border-bottom-left-radius:4px}.nc-msg-user{align-self:flex-end;background:#765a14;color:#fff;border-bottom-right-radius:4px}.nc-flyers{align-self:flex-start;width:82%;display:grid;grid-template-columns:1fr 1fr;gap:7px}.nc-flyer{display:block;width:100%;border-radius:10px;border:1px solid #E5E7EB;background:#fff;cursor:pointer;object-fit:cover}.nc-typing{align-self:flex-start;display:flex;gap:4px;padding:12px 14px;background:#fff;border:1px solid #E5E7EB;border-radius:14px}.nc-typing span{width:6px;height:6px;border-radius:50%;background:#B59449}#nc-input-row{display:flex;gap:8px;padding:12px;border-top:1px solid #E5E7EB;background:#fff}#nc-input{flex:1;border:1px solid #E5E7EB;background:#F3F3F6;border-radius:999px;padding:10px 14px;font-size:13.5px;outline:none}#nc-send{width:38px;height:38px;border-radius:999px;border:0;background:#765a14;color:#fff;cursor:pointer}#nc-send:disabled{opacity:.5}@media(max-width:480px){#nc-panel{position:fixed;inset:0;width:100vw;height:100vh;max-height:100vh;max-width:100vw;border-radius:0}#nativacare-widget-root{bottom:16px;right:16px}}`;
  var style=document.createElement("style");style.textContent=css;document.head.appendChild(style);
  var root=document.createElement("div");root.id="nativacare-widget-root";root.innerHTML='<div id="nc-panel"><div id="nc-header"><div><div id="nc-header-title">'+CLINIC_NAME+'</div><div id="nc-header-sub">Usually replies in a few minutes</div></div><button id="nc-close">✕</button></div><div id="nc-messages"></div><div id="nc-input-row"><input id="nc-input" type="text" placeholder="Type a message…" autocomplete="off"><button id="nc-send">➤</button></div></div><button id="nc-bubble" aria-label="Open chat">💬</button>';document.body.appendChild(root);
  var panel=root.querySelector("#nc-panel"),bubble=root.querySelector("#nc-bubble"),closeBtn=root.querySelector("#nc-close"),messagesEl=root.querySelector("#nc-messages"),inputEl=root.querySelector("#nc-input"),sendBtn=root.querySelector("#nc-send");
  function addMessage(text,who){var el=document.createElement("div");el.className="nc-msg nc-msg-"+who;el.textContent=text;messagesEl.appendChild(el);messagesEl.scrollTop=messagesEl.scrollHeight;}
  function absoluteMediaUrl(path){if(!path)return "";if(/^https?:\/\//i.test(path))return path;return API_BASE.replace(/\/$/,"")+"/"+String(path).replace(/^\//,"");}
  function addFlyers(flyers){if(!Array.isArray(flyers)||!flyers.length)return;var wrap=document.createElement("div");wrap.className="nc-flyers";flyers.forEach(function(path){var a=document.createElement("a");a.href=absoluteMediaUrl(path);a.target="_blank";a.rel="noopener";var img=document.createElement("img");img.className="nc-flyer";img.src=absoluteMediaUrl(path);img.alt="NativaCare service flyer";img.loading="lazy";img.onerror=function(){a.remove();if(!wrap.children.length)wrap.remove();};a.appendChild(img);wrap.appendChild(a);});messagesEl.appendChild(wrap);messagesEl.scrollTop=messagesEl.scrollHeight;}
  function showTyping(){var el=document.createElement("div");el.className="nc-typing";el.id="nc-typing-indicator";el.innerHTML="<span></span><span></span><span></span>";messagesEl.appendChild(el);}function hideTyping(){var el=document.getElementById("nc-typing-indicator");if(el)el.remove();}
  var sessionId=getSessionId(),sending=false,lastSeenMessageId=0,pollTimer=null;
  async function sendMessage(text,opts){opts=opts||{};if(!text||sending)return;sending=true;sendBtn.disabled=true;if(!opts.silent)addMessage(text,"user");inputEl.value="";showTyping();try{var res=await fetch(API_BASE.replace(/\/$/,"")+"/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId,message:text,source:"website"})});var data=await res.json();hideTyping();if(data.reply){addMessage(data.reply,"bot");addFlyers(data.flyers);}else if(!res.ok)addMessage("Sorry, something went wrong. Please try again in a moment.","bot");}catch(e){hideTyping();addMessage("Sorry, I couldn't reach the server. Please check your connection and try again.","bot");}finally{sending=false;sendBtn.disabled=false;inputEl.focus();}}
  async function pollForStaffReplies(){try{var res=await fetch(API_BASE.replace(/\/$/,"")+"/chat/"+encodeURIComponent(sessionId)+"/poll?after_id="+lastSeenMessageId);if(!res.ok)return;var data=await res.json();(data.messages||[]).forEach(function(m){addMessage(m.message,"bot");lastSeenMessageId=Math.max(lastSeenMessageId,m.id);});}catch(e){}}
  function startPolling(){if(!pollTimer)pollTimer=setInterval(pollForStaffReplies,4000)}function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
  function openPanel(){panel.classList.add("open");inputEl.focus();if(!messagesEl.children.length)sendMessage("hi",{silent:true});startPolling()}function closePanel(){panel.classList.remove("open");stopPolling()}
  bubble.addEventListener("click",function(){panel.classList.contains("open")?closePanel():openPanel()});closeBtn.addEventListener("click",closePanel);sendBtn.addEventListener("click",function(){sendMessage(inputEl.value.trim())});inputEl.addEventListener("keydown",function(e){if(e.key==="Enter")sendMessage(inputEl.value.trim())});
})();